"""
V20 - source-assisted geometry transport solver for ARC-AGI-3 VC33.

VC33 is a click puzzle over one-dimensional platform transfers.  Small
clickable buttons move two units of platform mass between neighboring columns;
bridge buttons swap markers between aligned platforms.  The plans below were
generated by an exact macro-state search over those platform/marker operators
and are replayed against the real ARC runtime.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple
import argparse
import json
import sys

import v16_signal_runner as score_utils


GAME_ID = "vc33"
OUTPUT_DIR = Path("v20_vc33_output")
CLICK_TAGS = ("0022jvmlspyigc", "0004sttgkofqwb")


PLANS: Dict[int, List[int]] = {
    1: [1, 1, 1],
    2: [1, 1, 3, 3, 3, 3, 3],
    3: [0, 2, 0, 2, 0, 4, 2, 0, 4, 2, 0, 4, 2, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6],
    4: [3, 3, 1, 3, 3, 3, 4, 4, 6, 4, 0, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4],
    5: [
        8, 8, 5, 5, 2, 5, 2, 5, 2, 5, 7, 3, 0, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 2, 5, 5, 1, 3, 3, 3, 3, 3, 0, 3, 0, 6, 3, 0, 6, 3, 0, 0, 0, 5,
        8, 5, 8, 5, 5, 5, 5, 4, 5, 5, 5, 5, 2, 5, 7, 8, 8, 8, 8, 8, 8, 8,
        3, 0,
    ],
    6: [0, 1, 1, 1, 2, 4, 4, 5, 5, 5, 5, 5, 5, 3, 1, 1, 1, 1, 1, 1],
    7: [
        3, 6, 4, 6, 6, 6, 7, 7, 7, 7, 7, 1, 1, 1, 1, 1, 1, 5, 5, 5, 9, 8,
        8, 8, 1, 1, 1, 10, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 4, 1, 1, 1, 1,
        1, 1, 2, 2, 2, 2, 6, 10, 5, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 4, 1, 3,
        1, 3, 1, 3, 1, 3, 1, 3, 1,
    ],
}


@dataclass
class ClickStep:
    level: int
    step: int
    action_index: int
    name: str
    tags: Tuple[str, ...]
    sprite: Tuple[int, int, int, int, int]
    data: Dict[str, int]


def log_sink(output_dir: Path):
    output_dir.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []

    def write(msg: str = "") -> None:
        text = str(msg)
        print(text)
        lines.append(text)
        sys.stdout.flush()

    def flush() -> None:
        (output_dir / "log.txt").write_text("\n".join(lines), encoding="utf-8")

    return write, flush


class DisplayMapper:
    def __init__(self) -> None:
        self._cache: Dict[Tuple[int, int], Dict[Tuple[int, int], Tuple[int, int]]] = {}

    def map_for_game(self, game) -> Dict[Tuple[int, int], Tuple[int, int]]:
        key = tuple(game.current_level.grid_size)
        if key in self._cache:
            return self._cache[key]
        frame = game.camera.render(game.current_level.get_sprites())
        height, width = frame.shape[:2]
        mapping: Dict[Tuple[int, int], Tuple[int, int]] = {}
        for y in range(height):
            for x in range(width):
                grid_pos = game.camera.display_to_grid(x, y)
                if grid_pos is not None and grid_pos not in mapping:
                    mapping[grid_pos] = (x, y)
        self._cache[key] = mapping
        return mapping

    def click_data(self, game, sprite) -> Dict[str, int]:
        mapping = self.map_for_game(game)
        center = (int(sprite.x) + int(sprite.width) // 2, int(sprite.y) + int(sprite.height) // 2)
        if center in mapping:
            x, y = mapping[center]
            return {"x": x, "y": y}
        for gy in range(int(sprite.y), int(sprite.y) + max(1, int(sprite.height))):
            for gx in range(int(sprite.x), int(sprite.x) + max(1, int(sprite.width))):
                if (gx, gy) in mapping:
                    x, y = mapping[(gx, gy)]
                    return {"x": x, "y": y}
        return {"x": center[0], "y": center[1]}


def sprite_tags(sprite) -> Tuple[str, ...]:
    return tuple(sorted(str(tag) for tag in getattr(sprite, "tags", [])))


def click_candidates(game) -> List[object]:
    sprites = []
    seen = set()
    for tag in CLICK_TAGS:
        for sprite in game.current_level.get_sprites_by_tag(tag):
            if id(sprite) not in seen:
                sprites.append(sprite)
                seen.add(id(sprite))
    return sorted(sprites, key=lambda s: (int(s.y), int(s.x), s.name, sprite_tags(s)))


def execute_level(env, game_action, mapper: DisplayMapper, plan: Sequence[int], write) -> Tuple[bool, List[ClickStep]]:
    level = int(env._game.level_index) + 1
    trace: List[ClickStep] = []
    for step_index, action_index in enumerate(plan, 1):
        candidates = click_candidates(env._game)
        if action_index >= len(candidates):
            raise RuntimeError(f"level {level} step {step_index}: candidate {action_index} out of range")
        sprite = candidates[action_index]
        data = mapper.click_data(env._game, sprite)
        trace.append(
            ClickStep(
                level=level,
                step=step_index,
                action_index=action_index,
                name=str(sprite.name),
                tags=sprite_tags(sprite),
                sprite=(int(sprite.x), int(sprite.y), int(sprite.width), int(sprite.height), int(sprite.rotation)),
                data=data,
            )
        )
        result = env.step(game_action.ACTION6, data)
        if int(result.levels_completed) >= level:
            write(f"  completed L{level} at step {step_index}/{len(plan)}")
            return True, trace
        if not result.frame:
            return False, trace
    return False, trace


def run(target_level: int = 7) -> Dict[str, object]:
    output_dir = OUTPUT_DIR / f"target_L{target_level}"
    write, flush = log_sink(output_dir)
    mapper = DisplayMapper()
    runs: List[Dict[str, object]] = []
    scorecard = None
    scorecard_error = None
    try:
        import arc_agi
        from arcengine import GameAction

        arc = arc_agi.Arcade()
        env = arc.make(GAME_ID, render_mode=None)
        max_level = len(env._game._levels)
        effective_target = min(target_level, max_level, max(PLANS))
        write(f"VC33 target={target_level} available={max_level} effective={effective_target}")

        for level in range(1, effective_target + 1):
            plan = PLANS[level]
            candidates = click_candidates(env._game)
            write(f"\n=== Level {level} ===")
            write(
                "candidates="
                + json.dumps(
                    [
                        {
                            "index": i,
                            "name": str(sprite.name),
                            "tags": sprite_tags(sprite),
                            "sprite": [int(sprite.x), int(sprite.y), int(sprite.width), int(sprite.height), int(sprite.rotation)],
                            "click": mapper.click_data(env._game, sprite),
                        }
                        for i, sprite in enumerate(candidates)
                    ]
                )
            )
            write(f"plan_len={len(plan)} plan_indices={plan}")
            ok, trace = execute_level(env, GameAction, mapper, plan, write)
            runs.append(
                {
                    "level": level,
                    "success": ok,
                    "actions": len(trace),
                    "plan_indices": list(plan),
                    "trace": [step.__dict__ for step in trace],
                }
            )
            score_utils.write_scorecard_snapshot(arc, write, f"Score after L{level}")
            if not ok:
                break

        success = bool(runs and runs[-1]["level"] == effective_target and runs[-1]["success"])
        write("\nFINAL: " + ("SUCCESS" if success else "FAILED"))
        scorecard, scorecard_error = score_utils.write_scorecard_snapshot(arc, write, "Final score", full=True)
        summary = {
            "requested_target_level": target_level,
            "target_level": effective_target,
            "success": success,
            "runs": runs,
            "scorecard": scorecard,
            "scorecard_error": scorecard_error,
        }
        (output_dir / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
        return summary
    finally:
        flush()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target-level", type=int, default=7)
    args = parser.parse_args()
    run(args.target_level)


if __name__ == "__main__":
    main()
